### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by divy-koushik-mishra**
Added some notes to README

### CODE REVIEW

**Comment by weyert** [comment]
Sorry, what's the added value of this? If it hasn't been touched in 12 years it's clearly not active

**Review by MichaelDeBoey — COMMENTED** [review]
Looks like spam to me... 😕

**Comment by divy-koushik-mishra** [comment]
Are you serious??? Okay..... Listen..... I am a beginner in this. You can
verify it from my profile... So I was noy having any idea.... But I promise
that I will not repeat this again

Regards

**Comment by divy-koushik-mishra** [comment]
> Sorry, what's the added value of this? If it hasn't been touched in 12 years it's clearly not active

And I have not added anything spammy. I just modified a file which tells the viewers that this repository is not active.

**Comment by weyert** [comment]
Personally, I don't see the added value of changing README to add this. As I think that no changes for twelve years makes it really obvious.

**Pull request closed without merging**
